### PR TITLE
Normalize audio using ffmpeg_normalize.

### PR DESCRIPTION
**Pull request by bohning**
This seems to accomplish what is needed, but in a more concise way than two external calls to ffmpeg.

### CODE REVIEW

**Comment by bohning** [comment]
I am just a little bit sceptic that the output of ffmpeg-normalize states `normalization_type: dynamic`, which is contradictory to the manual.
image

**Comment by mjhalwa** [comment]
As discussed in voice chat: This message seems to be an output from the first pass. I tested the proposed normalization with 3 of my songs (#65 ) + "Monsterparty". The comparison with my dynamic and linear results unveiled that the proposed method with ffmpeg_normalize does in fact produce linearly normalized results - even though the output states "dynamic". One of my samples (Circle of Life) even has an LRA of 16.2 and still was linearly normalized.

**Comment by bohning** [comment]
Open issues:
- importing ffmpeg-normalize messes up our TextEditLogger due to introduced log coloring (should be solved upstream in ffmpeg-normalize, @g3n35i5 offered to have a look at it)
- if normalization is checked and AudioFormat = M4A, we should probably drop the `ext=m4a` from the yt-dlp command so that it also downloads the .webm (which is then normalized and converted to an m4a in the process, as is the case when AudioFormat = MP3).

**Comment by g3n35i5** [comment]
> * importing ffmpeg-normalize messes up our TextEditLogger due to introduced log coloring (should be solved upstream in ffmpeg-normalize, @g3n35i5 offered to have a look at it)

https://github.com/slhck/ffmpeg-normalize/pull/216

**Comment by g3n35i5** [comment]
Ffmpeg normalize PR ist gemerged

**Comment by bohning** [comment]
> Ffmpeg normalize PR ist gemerged

Works like a charm now and does not mess up our own logging anymore.

**Review by RumovZ — APPROVED** [review]

**Pull request merged**
