### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mjhalwa**
adds instructions for setup in windows using wsl 2

### CODE REVIEW

**Comment by RumovZ** [comment]
Cool, thanks for figuring this out and sharing!
I think even if you have developer mode enabled and symlinks working (or if we remove the symlink in the future), this is a very useful guide, e.g. if you want to debug a UNIX error on a Windows machine. Maybe we can create a separate wiki page for it? Then in the README, we could link to that page.

**Comment by mjhalwa** [comment]
If you asked me:

Wiki or readme, both is fine for me, only I think i am not able to propose a wiki change via PR (can i?) in the main repo. So if you add an article in the wiki, I could modify my proposed change to the readme. Maybe you add a wiki page for "Setup" or "Installation" with chapters for each OS. I guess my originally proposed change to the readme would fit a "Windows" chapter.

If I understood correctly, I can simply add another commit to the feature branch in my repo and it is added to this PR automatically.

I'd change the readme to something like

``` md
either
- enable developer settings and use git's symlinks capabilities, see [this stackoverflow answer](https://example.com) or
- use WSL with at least Ubuntu 22.04, see [detailed instructions in wiki](https://example.com)
```

Where the wiki page link points to the "Windows" Chapter on a wiki page

**Comment by RumovZ** [comment]
Yes, exactly. Maybe @bohning can enable wiki edits for non-contributors?

**Comment by bohning** [comment]
> Yes, exactly. Maybe @bohning can enable wiki edits for non-contributors?

Just enabled the Wiki for non-contributors and also added @mjhalwa as a contributor.

**Pull request merged**
