### PR TITLE
Add debug console with REPL (Ctrl+.)

### PR DESCRIPTION
**Pull request by RumovZ**
This should make debugging easier, especially in windowed builds, where there isn't a console available.
Heads-up, @g3n35i5.

### CODE REVIEW

**Review by bohning — APPROVED** [review]

**Comment by RumovZ** [comment]
@bohning, here is a test script to try out:
```py
for song in mw.table._model.songs:
  if " feat " in song.data.artist:
    print(f"{song.data.artist} - {song.data.title}")
```

**Comment by bohning** [comment]
Nice, looking forward to trying it out. Thanks a lot!

**Comment by bohning** [comment]
Just tested it and got "no output" and thought at first I was doing something wrong, but then tested it with ` feat. ` and it works like a charm. Awesome!

**Comment by RumovZ** [comment]
Then someone (probably you) must have fixed that one song with "feat" in the meantime. 😄

**Comment by bohning** [comment]
Probaby me, yes ;-)

**Pull request merged**
